{
  "patcher": {
    "fileversion": 1,
    "appversion": { "major": 9, "minor": 0, "revision": 3, "architecture": "arm64", "modernui": 1 },
    "rect": [100.0, 100.0, 720.0, 420.0],
    "default_fontname": "Arial",
    "default_fontsize": 12.0,
    "boxes": [
      { "box": { "id": "in", "maxclass": "newobj", "text": "in 1", "patching_rect": [40.0, 35.0, 35.0, 22.0], "numinlets": 0, "numoutlets": 1 } },
      { "box": { "id": "route", "maxclass": "newobj", "text": "route grain", "patching_rect": [40.0, 75.0, 75.0, 22.0], "numinlets": 1, "numoutlets": 2 } },
      { "box": { "id": "order", "maxclass": "newobj", "text": "t l l", "patching_rect": [40.0, 105.0, 45.0, 22.0], "numinlets": 1, "numoutlets": 2 } },
      { "box": { "id": "unpack", "maxclass": "newobj", "text": "unpack 0. 0. 0. 0.", "patching_rect": [40.0, 115.0, 145.0, 22.0], "numinlets": 1, "numoutlets": 4 } },
      { "box": { "id": "packplay", "maxclass": "newobj", "text": "zl slice 3", "patching_rect": [40.0, 165.0, 70.0, 22.0], "numinlets": 2, "numoutlets": 2 } },
      { "box": { "id": "play", "maxclass": "newobj", "text": "play~ #1 1", "patching_rect": [40.0, 205.0, 75.0, 22.0], "numinlets": 3, "numoutlets": 2, "outlettype": ["signal", "bang"] } },
      { "box": { "id": "half", "maxclass": "newobj", "text": "* 0.5", "patching_rect": [210.0, 155.0, 45.0, 22.0], "numinlets": 2, "numoutlets": 1 } },
      { "box": { "id": "envmsg", "maxclass": "message", "text": "0., 1. $1, 0. $1 $1", "patching_rect": [210.0, 190.0, 135.0, 22.0], "numinlets": 2, "numoutlets": 1 } },
      { "box": { "id": "env", "maxclass": "newobj", "text": "line~", "patching_rect": [210.0, 225.0, 40.0, 22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "amp", "maxclass": "newobj", "text": "*~", "patching_rect": [40.0, 260.0, 35.0, 22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "panl", "maxclass": "newobj", "text": "expr sqrt(0.5*(1.-$f1))", "patching_rect": [380.0, 145.0, 160.0, 22.0], "numinlets": 1, "numoutlets": 1 } },
      { "box": { "id": "panr", "maxclass": "newobj", "text": "expr sqrt(0.5*(1.+$f1))", "patching_rect": [550.0, 145.0, 160.0, 22.0], "numinlets": 1, "numoutlets": 1 } },
      { "box": { "id": "panlp", "maxclass": "newobj", "text": "pack 0. 5", "patching_rect": [380.0, 180.0, 65.0, 22.0], "numinlets": 2, "numoutlets": 1 } },
      { "box": { "id": "panrp", "maxclass": "newobj", "text": "pack 0. 5", "patching_rect": [550.0, 180.0, 65.0, 22.0], "numinlets": 2, "numoutlets": 1 } },
      { "box": { "id": "panls", "maxclass": "newobj", "text": "line~", "patching_rect": [380.0, 215.0, 40.0, 22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "panrs", "maxclass": "newobj", "text": "line~", "patching_rect": [550.0, 215.0, 40.0, 22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "left", "maxclass": "newobj", "text": "*~", "patching_rect": [120.0, 305.0, 35.0, 22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "right", "maxclass": "newobj", "text": "*~", "patching_rect": [250.0, 305.0, 35.0, 22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "outl", "maxclass": "newobj", "text": "out~ 1", "patching_rect": [120.0, 355.0, 50.0, 22.0], "numinlets": 1, "numoutlets": 0 } },
      { "box": { "id": "outr", "maxclass": "newobj", "text": "out~ 2", "patching_rect": [250.0, 355.0, 50.0, 22.0], "numinlets": 1, "numoutlets": 0 } }
    ],
    "lines": [
      { "patchline": { "source": ["in",0], "destination": ["route",0] } },
      { "patchline": { "source": ["route",0], "destination": ["order",0] } },
      { "patchline": { "source": ["order",1], "destination": ["unpack",0] } },
      { "patchline": { "source": ["order",0], "destination": ["packplay",0] } },
      { "patchline": { "source": ["unpack",2], "destination": ["half",0] } },
      { "patchline": { "source": ["unpack",3], "destination": ["panl",0] } },
      { "patchline": { "source": ["unpack",3], "destination": ["panr",0] } },
      { "patchline": { "source": ["packplay",0], "destination": ["play",0] } },
      { "patchline": { "source": ["half",0], "destination": ["envmsg",0] } },
      { "patchline": { "source": ["envmsg",0], "destination": ["env",0] } },
      { "patchline": { "source": ["play",0], "destination": ["amp",0] } },
      { "patchline": { "source": ["env",0], "destination": ["amp",1] } },
      { "patchline": { "source": ["panl",0], "destination": ["panlp",0] } },
      { "patchline": { "source": ["panr",0], "destination": ["panrp",0] } },
      { "patchline": { "source": ["panlp",0], "destination": ["panls",0] } },
      { "patchline": { "source": ["panrp",0], "destination": ["panrs",0] } },
      { "patchline": { "source": ["amp",0], "destination": ["left",0] } },
      { "patchline": { "source": ["amp",0], "destination": ["right",0] } },
      { "patchline": { "source": ["panls",0], "destination": ["left",1] } },
      { "patchline": { "source": ["panrs",0], "destination": ["right",1] } },
      { "patchline": { "source": ["left",0], "destination": ["outl",0] } },
      { "patchline": { "source": ["right",0], "destination": ["outr",0] } }
    ]
  }
}
