{
  "patcher": {
    "fileversion": 1,
    "appversion": { "major": 9, "minor": 0, "revision": 3, "architecture": "arm64", "modernui": 1 },
    "rect": [120.0, 90.0, 1080.0, 680.0],
    "bgcolor": [0.09, 0.07, 0.10, 1.0],
    "openinpresentation": 1,
    "default_fontname": "Arial",
    "default_fontsize": 12.0,
    "boxes": [
      { "box": { "id": "title", "maxclass": "comment", "text": "GRANGRANDMA — LIVE MIC GRANULATOR", "fontsize": 24.0, "textcolor": [0.96,0.76,0.52,1.0], "patching_rect": [35.0,20.0,520.0,34.0], "presentation": 1, "presentation_rect": [35.0,20.0,520.0,34.0] } },
      { "box": { "id": "hint", "maxclass": "comment", "text": "Put on headphones, enable audio, then speak into input 1.", "textcolor": [0.75,0.68,0.74,1.0], "patching_rect": [38.0,56.0,440.0,20.0], "presentation": 1, "presentation_rect": [38.0,56.0,440.0,20.0] } },
      { "box": { "id": "mic", "maxclass": "newobj", "text": "adc~ 1", "patching_rect": [35.0,430.0,50.0,22.0], "numinlets": 1, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "buf", "maxclass": "newobj", "text": "buffer~ #0-live 4000 1", "patching_rect": [35.0,390.0,145.0,22.0], "numinlets": 1, "numoutlets": 2 } },
      { "box": { "id": "recordsum", "maxclass": "newobj", "text": "+~", "patching_rect": [115.0,465.0,35.0,22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "record", "maxclass": "newobj", "text": "record~ #0-live @loop 1", "patching_rect": [115.0,505.0,155.0,22.0], "numinlets": 3, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "snap", "maxclass": "newobj", "text": "snapshot~ 10", "patching_rect": [285.0,505.0,85.0,22.0], "numinlets": 2, "numoutlets": 1 } },
      { "box": { "id": "metro", "maxclass": "newobj", "text": "qmetro 83", "patching_rect": [410.0,465.0,70.0,22.0], "numinlets": 2, "numoutlets": 1 } },
      { "box": { "id": "sched", "maxclass": "newobj", "text": "js GrangrandMA-scheduler.js 32 4000", "patching_rect": [410.0,505.0,225.0,22.0], "numinlets": 5, "numoutlets": 1 } },
      { "box": { "id": "poly", "maxclass": "newobj", "text": "poly~ GrangrandMA-grainvoice 32 #0-live", "patching_rect": [410.0,545.0,250.0,22.0], "numinlets": 1, "numoutlets": 2, "outlettype": ["signal","signal"] } },
      { "box": { "id": "wetlscale", "maxclass": "newobj", "text": "*~ 0.5", "patching_rect": [410.0,585.0,50.0,22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "wetrscale", "maxclass": "newobj", "text": "*~ 0.5", "patching_rect": [500.0,585.0,50.0,22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "wetlclip", "maxclass": "newobj", "text": "clip~ -1. 1.", "patching_rect": [410.0,620.0,75.0,22.0], "numinlets": 3, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "wetrclip", "maxclass": "newobj", "text": "clip~ -1. 1.", "patching_rect": [500.0,620.0,75.0,22.0], "numinlets": 3, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "wetmono", "maxclass": "newobj", "text": "+~", "patching_rect": [680.0,550.0,35.0,22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "wetmonohalf", "maxclass": "newobj", "text": "*~ 0.5", "patching_rect": [680.0,585.0,50.0,22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "fbamp", "maxclass": "newobj", "text": "*~", "patching_rect": [680.0,620.0,35.0,22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "fbpack", "maxclass": "newobj", "text": "pack 0. 25", "patching_rect": [760.0,465.0,75.0,22.0], "numinlets": 2, "numoutlets": 1 } },
      { "box": { "id": "fbline", "maxclass": "newobj", "text": "line~", "patching_rect": [760.0,505.0,40.0,22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "wetampL", "maxclass": "newobj", "text": "*~", "patching_rect": [810.0,550.0,35.0,22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "wetampR", "maxclass": "newobj", "text": "*~", "patching_rect": [860.0,550.0,35.0,22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "dryampL", "maxclass": "newobj", "text": "*~", "patching_rect": [810.0,590.0,35.0,22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "dryampR", "maxclass": "newobj", "text": "*~", "patching_rect": [860.0,590.0,35.0,22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "outsumL", "maxclass": "newobj", "text": "+~", "patching_rect": [810.0,625.0,35.0,22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "outsumR", "maxclass": "newobj", "text": "+~", "patching_rect": [860.0,625.0,35.0,22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "dac", "maxclass": "ezdac~", "patching_rect": [955.0,585.0,45.0,45.0], "numinlets": 2, "numoutlets": 0, "presentation": 1, "presentation_rect": [925.0,80.0,55.0,55.0] } },
      { "box": { "id": "dspcomment", "maxclass": "comment", "text": "AUDIO", "textcolor": [0.96,0.76,0.52,1.0], "patching_rect": [920.0,55.0,70.0,20.0], "presentation": 1, "presentation_rect": [925.0,55.0,70.0,20.0] } },
      { "box": { "id": "run", "maxclass": "toggle", "patching_rect": [400.0,430.0,24.0,24.0], "numinlets": 1, "numoutlets": 1 } },
      { "box": { "id": "runload", "maxclass": "newobj", "text": "loadmess 1", "patching_rect": [400.0,390.0,75.0,22.0], "numinlets": 1, "numoutlets": 1 } },
      { "box": { "id": "size", "maxclass": "flonum", "minimum": 20.0, "maximum": 500.0, "patching_rect": [55.0,145.0,75.0,24.0], "numinlets": 1, "numoutlets": 2, "presentation": 1, "presentation_rect": [55.0,145.0,75.0,24.0] } },
      { "box": { "id": "sizelabel", "maxclass": "comment", "text": "SIZE (ms)", "textcolor": [0.85,0.80,0.84,1.0], "patching_rect": [55.0,120.0,90.0,20.0], "presentation": 1, "presentation_rect": [55.0,120.0,90.0,20.0] } },
      { "box": { "id": "sizeload", "maxclass": "newobj", "text": "loadmess 120.", "patching_rect": [55.0,350.0,90.0,22.0], "numinlets": 1, "numoutlets": 1 } },
      { "box": { "id": "density", "maxclass": "flonum", "minimum": 1.0, "maximum": 50.0, "patching_rect": [190.0,145.0,75.0,24.0], "numinlets": 1, "numoutlets": 2, "presentation": 1, "presentation_rect": [190.0,145.0,75.0,24.0] } },
      { "box": { "id": "densitylabel", "maxclass": "comment", "text": "DENSITY", "textcolor": [0.85,0.80,0.84,1.0], "patching_rect": [190.0,120.0,90.0,20.0], "presentation": 1, "presentation_rect": [190.0,120.0,90.0,20.0] } },
      { "box": { "id": "densityload", "maxclass": "newobj", "text": "loadmess 12.", "patching_rect": [180.0,350.0,85.0,22.0], "numinlets": 1, "numoutlets": 1 } },
      { "box": { "id": "densityexpr", "maxclass": "newobj", "text": "expr 1000./max(0.1\\,$f1)", "patching_rect": [270.0,430.0,150.0,22.0], "numinlets": 1, "numoutlets": 1 } },
      { "box": { "id": "pitch", "maxclass": "flonum", "minimum": -24.0, "maximum": 24.0, "patching_rect": [325.0,145.0,75.0,24.0], "numinlets": 1, "numoutlets": 2, "presentation": 1, "presentation_rect": [325.0,145.0,75.0,24.0] } },
      { "box": { "id": "pitchlabel", "maxclass": "comment", "text": "PITCH (st)", "textcolor": [0.85,0.80,0.84,1.0], "patching_rect": [325.0,120.0,90.0,20.0], "presentation": 1, "presentation_rect": [325.0,120.0,90.0,20.0] } },
      { "box": { "id": "pitchload", "maxclass": "newobj", "text": "loadmess 0.", "patching_rect": [285.0,350.0,75.0,22.0], "numinlets": 1, "numoutlets": 1 } },
      { "box": { "id": "position", "maxclass": "flonum", "minimum": 0.0, "maximum": 1.0, "patching_rect": [460.0,145.0,75.0,24.0], "numinlets": 1, "numoutlets": 2, "presentation": 1, "presentation_rect": [460.0,145.0,75.0,24.0] } },
      { "box": { "id": "positionlabel", "maxclass": "comment", "text": "POSITION", "textcolor": [0.85,0.80,0.84,1.0], "patching_rect": [460.0,120.0,90.0,20.0], "presentation": 1, "presentation_rect": [460.0,120.0,90.0,20.0] } },
      { "box": { "id": "positionload", "maxclass": "newobj", "text": "loadmess 0.", "patching_rect": [380.0,350.0,75.0,22.0], "numinlets": 1, "numoutlets": 1 } },
      { "box": { "id": "spray", "maxclass": "flonum", "minimum": 0.0, "maximum": 1.0, "patching_rect": [595.0,145.0,75.0,24.0], "numinlets": 1, "numoutlets": 2, "presentation": 1, "presentation_rect": [595.0,145.0,75.0,24.0] } },
      { "box": { "id": "spraylabel", "maxclass": "comment", "text": "SPRAY", "textcolor": [0.85,0.80,0.84,1.0], "patching_rect": [595.0,120.0,90.0,20.0], "presentation": 1, "presentation_rect": [595.0,120.0,90.0,20.0] } },
      { "box": { "id": "sprayload", "maxclass": "newobj", "text": "loadmess 0.12", "patching_rect": [475.0,350.0,85.0,22.0], "numinlets": 1, "numoutlets": 1 } },
      { "box": { "id": "feedback", "maxclass": "flonum", "minimum": 0.0, "maximum": 0.9, "patching_rect": [730.0,145.0,75.0,24.0], "numinlets": 1, "numoutlets": 2, "presentation": 1, "presentation_rect": [730.0,145.0,75.0,24.0] } },
      { "box": { "id": "feedbacklabel", "maxclass": "comment", "text": "FEEDBACK", "textcolor": [0.85,0.80,0.84,1.0], "patching_rect": [730.0,120.0,90.0,20.0], "presentation": 1, "presentation_rect": [730.0,120.0,90.0,20.0] } },
      { "box": { "id": "feedbackload", "maxclass": "newobj", "text": "loadmess 0.15", "patching_rect": [580.0,350.0,85.0,22.0], "numinlets": 1, "numoutlets": 1 } },
      { "box": { "id": "mix", "maxclass": "flonum", "minimum": 0.0, "maximum": 1.0, "patching_rect": [865.0,145.0,75.0,24.0], "numinlets": 1, "numoutlets": 2, "presentation": 1, "presentation_rect": [865.0,145.0,75.0,24.0] } },
      { "box": { "id": "mixlabel", "maxclass": "comment", "text": "MIX", "textcolor": [0.85,0.80,0.84,1.0], "patching_rect": [865.0,120.0,90.0,20.0], "presentation": 1, "presentation_rect": [865.0,120.0,90.0,20.0] } },
      { "box": { "id": "mixload", "maxclass": "newobj", "text": "loadmess 0.65", "patching_rect": [685.0,350.0,85.0,22.0], "numinlets": 1, "numoutlets": 1 } },
      { "box": { "id": "mixtrigger", "maxclass": "newobj", "text": "t f f", "patching_rect": [760.0,390.0,45.0,22.0], "numinlets": 1, "numoutlets": 2 } },
      { "box": { "id": "wetpack", "maxclass": "newobj", "text": "pack 0. 25", "patching_rect": [820.0,430.0,75.0,22.0], "numinlets": 2, "numoutlets": 1 } },
      { "box": { "id": "wetline", "maxclass": "newobj", "text": "line~", "patching_rect": [820.0,470.0,40.0,22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } },
      { "box": { "id": "dryexpr", "maxclass": "newobj", "text": "expr 1.-$f1", "patching_rect": [905.0,390.0,75.0,22.0], "numinlets": 1, "numoutlets": 1 } },
      { "box": { "id": "drypack", "maxclass": "newobj", "text": "pack 0. 25", "patching_rect": [920.0,430.0,75.0,22.0], "numinlets": 2, "numoutlets": 1 } },
      { "box": { "id": "dryline", "maxclass": "newobj", "text": "line~", "patching_rect": [920.0,470.0,40.0,22.0], "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"] } }
    ],
    "lines": [
      { "patchline": { "source": ["mic",0], "destination": ["recordsum",0] } },
      { "patchline": { "source": ["fbamp",0], "destination": ["recordsum",1] } },
      { "patchline": { "source": ["recordsum",0], "destination": ["record",0] } },
      { "patchline": { "source": ["record",0], "destination": ["snap",0] } },
      { "patchline": { "source": ["snap",0], "destination": ["sched",0] } },
      { "patchline": { "source": ["metro",0], "destination": ["sched",0] } },
      { "patchline": { "source": ["sched",0], "destination": ["poly",0] } },
      { "patchline": { "source": ["poly",0], "destination": ["wetlscale",0] } },
      { "patchline": { "source": ["poly",1], "destination": ["wetrscale",0] } },
      { "patchline": { "source": ["wetlscale",0], "destination": ["wetlclip",0] } },
      { "patchline": { "source": ["wetrscale",0], "destination": ["wetrclip",0] } },
      { "patchline": { "source": ["wetlclip",0], "destination": ["wetmono",0] } },
      { "patchline": { "source": ["wetrclip",0], "destination": ["wetmono",1] } },
      { "patchline": { "source": ["wetmono",0], "destination": ["wetmonohalf",0] } },
      { "patchline": { "source": ["wetmonohalf",0], "destination": ["fbamp",0] } },
      { "patchline": { "source": ["fbline",0], "destination": ["fbamp",1] } },
      { "patchline": { "source": ["wetlclip",0], "destination": ["wetampL",0] } },
      { "patchline": { "source": ["wetrclip",0], "destination": ["wetampR",0] } },
      { "patchline": { "source": ["wetline",0], "destination": ["wetampL",1] } },
      { "patchline": { "source": ["wetline",0], "destination": ["wetampR",1] } },
      { "patchline": { "source": ["mic",0], "destination": ["dryampL",0] } },
      { "patchline": { "source": ["mic",0], "destination": ["dryampR",0] } },
      { "patchline": { "source": ["dryline",0], "destination": ["dryampL",1] } },
      { "patchline": { "source": ["dryline",0], "destination": ["dryampR",1] } },
      { "patchline": { "source": ["wetampL",0], "destination": ["outsumL",0] } },
      { "patchline": { "source": ["dryampL",0], "destination": ["outsumL",1] } },
      { "patchline": { "source": ["wetampR",0], "destination": ["outsumR",0] } },
      { "patchline": { "source": ["dryampR",0], "destination": ["outsumR",1] } },
      { "patchline": { "source": ["outsumL",0], "destination": ["dac",0] } },
      { "patchline": { "source": ["outsumR",0], "destination": ["dac",1] } },
      { "patchline": { "source": ["runload",0], "destination": ["run",0] } },
      { "patchline": { "source": ["run",0], "destination": ["record",0] } },
      { "patchline": { "source": ["run",0], "destination": ["metro",0] } },
      { "patchline": { "source": ["sizeload",0], "destination": ["size",0] } },
      { "patchline": { "source": ["size",0], "destination": ["sched",1] } },
      { "patchline": { "source": ["densityload",0], "destination": ["density",0] } },
      { "patchline": { "source": ["density",0], "destination": ["densityexpr",0] } },
      { "patchline": { "source": ["densityexpr",0], "destination": ["metro",1] } },
      { "patchline": { "source": ["pitchload",0], "destination": ["pitch",0] } },
      { "patchline": { "source": ["pitch",0], "destination": ["sched",2] } },
      { "patchline": { "source": ["positionload",0], "destination": ["position",0] } },
      { "patchline": { "source": ["position",0], "destination": ["sched",3] } },
      { "patchline": { "source": ["sprayload",0], "destination": ["spray",0] } },
      { "patchline": { "source": ["spray",0], "destination": ["sched",4] } },
      { "patchline": { "source": ["feedbackload",0], "destination": ["feedback",0] } },
      { "patchline": { "source": ["feedback",0], "destination": ["fbpack",0] } },
      { "patchline": { "source": ["fbpack",0], "destination": ["fbline",0] } },
      { "patchline": { "source": ["mixload",0], "destination": ["mix",0] } },
      { "patchline": { "source": ["mix",0], "destination": ["mixtrigger",0] } },
      { "patchline": { "source": ["mixtrigger",0], "destination": ["wetpack",0] } },
      { "patchline": { "source": ["mixtrigger",1], "destination": ["dryexpr",0] } },
      { "patchline": { "source": ["wetpack",0], "destination": ["wetline",0] } },
      { "patchline": { "source": ["dryexpr",0], "destination": ["drypack",0] } },
      { "patchline": { "source": ["drypack",0], "destination": ["dryline",0] } }
    ]
  }
}
